language: julia
os:
  - linux
  - osx
  - windows
julia:
  - 1.2
coveralls: true
notifications:
  email: false
jobs:
  allow_failures:
    - julia: 1.3
  fast_finish: true
  include:
    - os: windows
      arch: x86
      julia: 1.2
    - os: linux
      julia: 1.3
